/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Location: () => import('#controllers/location_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Organization: () => import('#controllers/organization_controller'),
  Session: () => import('#controllers/session_controller'),
}
