/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  LeadOwner: () => import('#controllers/lead_owner_controller'),
  Location: () => import('#controllers/location_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Organization: () => import('#controllers/organization_controller'),
  OrganizationProfile: () => import('#controllers/organization_profile_controller'),
  Session: () => import('#controllers/session_controller'),
  Masters: () => import('#controllers/masters_controller'),
  Settings: () => import('#controllers/settings_controller'),
}
