/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CitySchema extends BaseModel {
  static $columns = ['countryCode', 'countryId', 'createdAt', 'flag', 'id', 'latitude', 'longitude', 'name', 'stateCode', 'stateId', 'updatedAt', 'wikiDataId'] as const
  $columns = CitySchema.$columns
  @column()
  declare countryCode: string
  @column()
  declare countryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare flag: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: string
  @column()
  declare longitude: string
  @column()
  declare name: string
  @column()
  declare stateCode: string
  @column()
  declare stateId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare wikiDataId: string | null
}

export class CountrySchema extends BaseModel {
  static $columns = ['capital', 'createdAt', 'currency', 'currencyName', 'currencySymbol', 'emoji', 'emojiU', 'flag', 'id', 'iso2', 'iso3', 'latitude', 'longitude', 'name', 'nationality', 'native', 'numericCode', 'phonecode', 'region', 'regionId', 'subregion', 'subregionId', 'timezones', 'tld', 'translations', 'updatedAt', 'wikiDataId'] as const
  $columns = CountrySchema.$columns
  @column()
  declare capital: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currency: string | null
  @column()
  declare currencyName: string | null
  @column()
  declare currencySymbol: string | null
  @column()
  declare emoji: string | null
  @column()
  declare emojiU: string | null
  @column()
  declare flag: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare iso2: string | null
  @column()
  declare iso3: string | null
  @column()
  declare latitude: string | null
  @column()
  declare longitude: string | null
  @column()
  declare name: string
  @column()
  declare nationality: string | null
  @column()
  declare native: string | null
  @column()
  declare numericCode: string | null
  @column()
  declare phonecode: string | null
  @column()
  declare region: string | null
  @column()
  declare regionId: number | null
  @column()
  declare subregion: string | null
  @column()
  declare subregionId: number | null
  @column()
  declare timezones: string | null
  @column()
  declare tld: string | null
  @column()
  declare translations: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare wikiDataId: string | null
}

export class FiscalYearSchema extends BaseModel {
  static $columns = ['createdAt', 'endDate', 'id', 'isActive', 'name', 'orgId', 'startDate', 'updatedAt'] as const
  $columns = FiscalYearSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare endDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column()
  declare orgId: number
  @column.date()
  declare startDate: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LeadOwnerSchema extends BaseModel {
  static $columns = ['createdAt', 'designation', 'email', 'id', 'name', 'phone', 'status', 'updatedAt'] as const
  $columns = LeadOwnerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare designation: string | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare status: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ModuleAddonSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isActive', 'moduleId', 'name', 'sortOrder', 'type', 'updatedAt'] as const
  $columns = ModuleAddonSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare moduleId: number
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ModuleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isActive', 'isComingSoon', 'isMandatory', 'key', 'label', 'sortOrder', 'updatedAt'] as const
  $columns = ModuleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isComingSoon: boolean
  @column()
  declare isMandatory: boolean
  @column()
  declare key: string
  @column()
  declare label: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrganizationModuleConfigSchema extends BaseModel {
  static $columns = ['addonIds', 'createdAt', 'enabled', 'id', 'moduleId', 'orgId'] as const
  $columns = OrganizationModuleConfigSchema.$columns
  @column()
  declare addonIds: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare moduleId: number
  @column()
  declare orgId: number
}

export class OrganizationProfilePermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'moduleId', 'orgId', 'permissions', 'profileId', 'updatedAt'] as const
  $columns = OrganizationProfilePermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare moduleId: number
  @column()
  declare orgId: number
  @column()
  declare permissions: any
  @column()
  declare profileId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrganizationProfileSchema extends BaseModel {
  static $columns = ['createdAt', 'dataAccess', 'description', 'id', 'name', 'orgId', 'updatedAt'] as const
  $columns = OrganizationProfileSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dataAccess: string
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare orgId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrganizationUserSchema extends BaseModel {
  static $columns = ['companyEmail', 'createdAt', 'dateOfBirth', 'employeeCode', 'fullName', 'gender', 'id', 'isActive', 'orgId', 'passwordHash', 'phone', 'profileId', 'sendWelcomeMail', 'updatedAt'] as const
  $columns = OrganizationUserSchema.$columns
  @column()
  declare companyEmail: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateOfBirth: DateTime | null
  @column()
  declare employeeCode: string | null
  @column()
  declare fullName: string
  @column()
  declare gender: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare orgId: number
  @column()
  declare passwordHash: string
  @column()
  declare phone: string | null
  @column()
  declare profileId: number | null
  @column()
  declare sendWelcomeMail: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['about', 'address', 'city', 'companySize', 'country', 'createdAt', 'currency', 'dateFormat', 'deletedAt', 'email', 'fiscalEnd', 'fiscalName', 'fiscalStart', 'gstNo', 'id', 'industry', 'isArchived', 'leadOwnerId', 'logo', 'name', 'orgId', 'parentOrgId', 'phone', 'planEnd', 'planStart', 'planType', 'slug', 'status', 'timeFormat', 'timezone', 'updatedAt', 'userLimit', 'website'] as const
  $columns = OrganizationSchema.$columns
  @column()
  declare about: string | null
  @column()
  declare address: string | null
  @column()
  declare city: string | null
  @column()
  declare companySize: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string | null
  @column()
  declare dateFormat: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column.date()
  declare fiscalEnd: DateTime | null
  @column()
  declare fiscalName: string | null
  @column.date()
  declare fiscalStart: DateTime | null
  @column()
  declare gstNo: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare industry: string | null
  @column()
  declare isArchived: boolean | null
  @column()
  declare leadOwnerId: number | null
  @column()
  declare logo: string | null
  @column()
  declare name: string
  @column()
  declare orgId: string
  @column()
  declare parentOrgId: number | null
  @column()
  declare phone: string | null
  @column.date()
  declare planEnd: DateTime | null
  @column.date()
  declare planStart: DateTime | null
  @column()
  declare planType: boolean
  @column()
  declare slug: string | null
  @column()
  declare status: boolean
  @column()
  declare timeFormat: string | null
  @column()
  declare timezone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userLimit: number | null
  @column()
  declare website: string | null
}

export class RegionSchema extends BaseModel {
  static $columns = ['createdAt', 'flag', 'id', 'name', 'translations', 'updatedAt', 'wikiDataId'] as const
  $columns = RegionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare flag: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare translations: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare wikiDataId: string | null
}

export class StateSchema extends BaseModel {
  static $columns = ['countryCode', 'countryId', 'createdAt', 'fipsCode', 'flag', 'id', 'iso2', 'latitude', 'longitude', 'name', 'type', 'updatedAt', 'wikiDataId'] as const
  $columns = StateSchema.$columns
  @column()
  declare countryCode: string
  @column()
  declare countryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare fipsCode: string | null
  @column()
  declare flag: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare iso2: string | null
  @column()
  declare latitude: string | null
  @column()
  declare longitude: string | null
  @column()
  declare name: string
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare wikiDataId: string | null
}

export class SubregionSchema extends BaseModel {
  static $columns = ['createdAt', 'flag', 'id', 'name', 'regionId', 'translations', 'updatedAt', 'wikiDataId'] as const
  $columns = SubregionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare flag: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare regionId: number
  @column()
  declare translations: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare wikiDataId: string | null
}

export class SystemSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'updatedAt', 'value'] as const
  $columns = SystemSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'googleId', 'id', 'isActive', 'password', 'totpSecret', 'totpVerified', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column()
  declare googleId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare totpSecret: string | null
  @column()
  declare totpVerified: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
