/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class FiscalYearSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'name', 'startDate', 'endDate', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = FiscalYearSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare name: string
  @column.date()
  declare startDate: DateTime
  @column.date()
  declare endDate: DateTime
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrganizationAddonSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'addonKey', 'enabled', 'createdAt'] as const
  $columns = OrganizationAddonSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare addonKey: string
  @column()
  declare enabled: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class OrganizationModuleSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'moduleKey', 'enabled', 'createdAt'] as const
  $columns = OrganizationModuleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare moduleKey: string
  @column()
  declare enabled: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class OrganizationUserSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'employeeCode', 'fullName', 'gender', 'phone', 'dateOfBirth', 'companyEmail', 'passwordHash', 'sendWelcomeMail', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = OrganizationUserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare employeeCode: string | null
  @column()
  declare fullName: string
  @column()
  declare gender: string | null
  @column()
  declare phone: string | null
  @column.date()
  declare dateOfBirth: DateTime | null
  @column()
  declare companyEmail: string
  @column()
  declare passwordHash: string
  @column()
  declare sendWelcomeMail: boolean | null
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'name', 'slug', 'logo', 'companySize', 'industry', 'website', 'about', 'gstNo', 'parentOrgId', 'fiscalName', 'fiscalStart', 'fiscalEnd', 'country', 'city', 'phone', 'email', 'address', 'leadOwnerId', 'currency', 'timezone', 'dateFormat', 'timeFormat', 'planType', 'userLimit', 'planStart', 'planEnd', 'status', 'isArchived', 'deletedAt', 'createdAt', 'updatedAt'] as const
  $columns = OrganizationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: string
  @column()
  declare name: string
  @column()
  declare slug: string | null
  @column()
  declare logo: string | null
  @column()
  declare companySize: string | null
  @column()
  declare industry: string | null
  @column()
  declare website: string | null
  @column()
  declare about: string | null
  @column()
  declare gstNo: string | null
  @column()
  declare parentOrgId: number | null
  @column()
  declare fiscalName: string | null
  @column.date()
  declare fiscalStart: DateTime | null
  @column.date()
  declare fiscalEnd: DateTime | null
  @column()
  declare country: string | null
  @column()
  declare city: string | null
  @column()
  declare phone: string | null
  @column()
  declare email: string | null
  @column()
  declare address: string | null
  @column()
  declare leadOwnerId: number | null
  @column()
  declare currency: string | null
  @column()
  declare timezone: string | null
  @column()
  declare dateFormat: string | null
  @column()
  declare timeFormat: string | null
  @column()
  declare planType: string | null
  @column()
  declare userLimit: number | null
  @column.date()
  declare planStart: DateTime | null
  @column.date()
  declare planEnd: DateTime | null
  @column()
  declare status: string | null
  @column()
  declare isArchived: boolean | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProfilePermissionSchema extends BaseModel {
  static $columns = ['id', 'profileId', 'moduleKey', 'featureKey', 'canView', 'canAdd', 'canEdit', 'canDelete', 'createdAt'] as const
  $columns = ProfilePermissionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare profileId: number
  @column()
  declare moduleKey: string
  @column()
  declare featureKey: string
  @column()
  declare canView: boolean | null
  @column()
  declare canAdd: boolean | null
  @column()
  declare canEdit: boolean | null
  @column()
  declare canDelete: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class SystemSettingSchema extends BaseModel {
  static $columns = ['id', 'key', 'value', 'createdAt', 'updatedAt'] as const
  $columns = SystemSettingSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare value: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserProfileSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'name', 'description', 'dataAccess', 'createdAt', 'updatedAt'] as const
  $columns = UserProfileSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column()
  declare dataAccess: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'email', 'password', 'googleId', 'totpSecret', 'totpVerified', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare googleId: string | null
  @column()
  declare totpSecret: string | null
  @column()
  declare totpVerified: boolean | null
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
