/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'hrms.login': {
    methods: ["GET","HEAD"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['hrms.login']['types'],
  },
  'hrms.login.submit': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['hrms.login.submit']['types'],
  },
  'auth.login': {
    methods: ["GET","HEAD"],
    pattern: '/orgbuilder/login',
    tokens: [{"old":"/orgbuilder/login","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.login.store': {
    methods: ["POST"],
    pattern: '/orgbuilder/login',
    tokens: [{"old":"/orgbuilder/login","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login.store']['types'],
  },
  'auth.google': {
    methods: ["GET","HEAD"],
    pattern: '/auth/google',
    tokens: [{"old":"/auth/google","type":0,"val":"auth","end":""},{"old":"/auth/google","type":0,"val":"google","end":""}],
    types: placeholder as Registry['auth.google']['types'],
  },
  'auth.google.callback': {
    methods: ["GET","HEAD"],
    pattern: '/auth/google/callback',
    tokens: [{"old":"/auth/google/callback","type":0,"val":"auth","end":""},{"old":"/auth/google/callback","type":0,"val":"google","end":""},{"old":"/auth/google/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['auth.google.callback']['types'],
  },
  'auth.totp.verify': {
    methods: ["GET","HEAD"],
    pattern: '/auth/totp/verify',
    tokens: [{"old":"/auth/totp/verify","type":0,"val":"auth","end":""},{"old":"/auth/totp/verify","type":0,"val":"totp","end":""},{"old":"/auth/totp/verify","type":0,"val":"verify","end":""}],
    types: placeholder as Registry['auth.totp.verify']['types'],
  },
  'auth.totp.verify.store': {
    methods: ["POST"],
    pattern: '/auth/totp/verify',
    tokens: [{"old":"/auth/totp/verify","type":0,"val":"auth","end":""},{"old":"/auth/totp/verify","type":0,"val":"totp","end":""},{"old":"/auth/totp/verify","type":0,"val":"verify","end":""}],
    types: placeholder as Registry['auth.totp.verify.store']['types'],
  },
  'auth.totp.setup': {
    methods: ["GET","HEAD"],
    pattern: '/auth/totp/setup',
    tokens: [{"old":"/auth/totp/setup","type":0,"val":"auth","end":""},{"old":"/auth/totp/setup","type":0,"val":"totp","end":""},{"old":"/auth/totp/setup","type":0,"val":"setup","end":""}],
    types: placeholder as Registry['auth.totp.setup']['types'],
  },
  'auth.totp.setup.store': {
    methods: ["POST"],
    pattern: '/auth/totp/setup',
    tokens: [{"old":"/auth/totp/setup","type":0,"val":"auth","end":""},{"old":"/auth/totp/setup","type":0,"val":"totp","end":""},{"old":"/auth/totp/setup","type":0,"val":"setup","end":""}],
    types: placeholder as Registry['auth.totp.setup.store']['types'],
  },
  'auth.logout': {
    methods: ["POST"],
    pattern: '/orgbuilder/logout',
    tokens: [{"old":"/orgbuilder/logout","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.logout']['types'],
  },
  'api.countries': {
    methods: ["GET","HEAD"],
    pattern: '/api/countries',
    tokens: [{"old":"/api/countries","type":0,"val":"api","end":""},{"old":"/api/countries","type":0,"val":"countries","end":""}],
    types: placeholder as Registry['api.countries']['types'],
  },
  'api.cities': {
    methods: ["GET","HEAD"],
    pattern: '/api/cities',
    tokens: [{"old":"/api/cities","type":0,"val":"api","end":""},{"old":"/api/cities","type":0,"val":"cities","end":""}],
    types: placeholder as Registry['api.cities']['types'],
  },
  'api.currencies': {
    methods: ["GET","HEAD"],
    pattern: '/api/currencies',
    tokens: [{"old":"/api/currencies","type":0,"val":"api","end":""},{"old":"/api/currencies","type":0,"val":"currencies","end":""}],
    types: placeholder as Registry['api.currencies']['types'],
  },
  'api.timezones': {
    methods: ["GET","HEAD"],
    pattern: '/api/timezones',
    tokens: [{"old":"/api/timezones","type":0,"val":"api","end":""},{"old":"/api/timezones","type":0,"val":"timezones","end":""}],
    types: placeholder as Registry['api.timezones']['types'],
  },
  'api.modules': {
    methods: ["GET","HEAD"],
    pattern: '/api/modules',
    tokens: [{"old":"/api/modules","type":0,"val":"api","end":""},{"old":"/api/modules","type":0,"val":"modules","end":""}],
    types: placeholder as Registry['api.modules']['types'],
  },
  'api.lead_owners': {
    methods: ["GET","HEAD"],
    pattern: '/api/lead-owners',
    tokens: [{"old":"/api/lead-owners","type":0,"val":"api","end":""},{"old":"/api/lead-owners","type":0,"val":"lead-owners","end":""}],
    types: placeholder as Registry['api.lead_owners']['types'],
  },
  'api.orgs.search': {
    methods: ["GET","HEAD"],
    pattern: '/api/orgs/search',
    tokens: [{"old":"/api/orgs/search","type":0,"val":"api","end":""},{"old":"/api/orgs/search","type":0,"val":"orgs","end":""},{"old":"/api/orgs/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['api.orgs.search']['types'],
  },
  'dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/orgbuilder/dashboard',
    tokens: [{"old":"/orgbuilder/dashboard","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['dashboard']['types'],
  },
  'organizations.index': {
    methods: ["GET","HEAD"],
    pattern: '/orgbuilder/organizations',
    tokens: [{"old":"/orgbuilder/organizations","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations","type":0,"val":"organizations","end":""}],
    types: placeholder as Registry['organizations.index']['types'],
  },
  'organizations.create': {
    methods: ["GET","HEAD"],
    pattern: '/orgbuilder/organizations/create',
    tokens: [{"old":"/orgbuilder/organizations/create","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/create","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['organizations.create']['types'],
  },
  'organizations.store': {
    methods: ["POST"],
    pattern: '/orgbuilder/organizations',
    tokens: [{"old":"/orgbuilder/organizations","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations","type":0,"val":"organizations","end":""}],
    types: placeholder as Registry['organizations.store']['types'],
  },
  'organizations.bulk': {
    methods: ["POST"],
    pattern: '/orgbuilder/organizations/bulk',
    tokens: [{"old":"/orgbuilder/organizations/bulk","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/bulk","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['organizations.bulk']['types'],
  },
  'organizations.export': {
    methods: ["GET","HEAD"],
    pattern: '/orgbuilder/organizations/export',
    tokens: [{"old":"/orgbuilder/organizations/export","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/export","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['organizations.export']['types'],
  },
  'organizations.checkEmail': {
    methods: ["GET","HEAD"],
    pattern: '/orgbuilder/organizations/check-email',
    tokens: [{"old":"/orgbuilder/organizations/check-email","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/check-email","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/check-email","type":0,"val":"check-email","end":""}],
    types: placeholder as Registry['organizations.checkEmail']['types'],
  },
  'organizations.checkPhone': {
    methods: ["GET","HEAD"],
    pattern: '/orgbuilder/organizations/check-phone',
    tokens: [{"old":"/orgbuilder/organizations/check-phone","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/check-phone","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/check-phone","type":0,"val":"check-phone","end":""}],
    types: placeholder as Registry['organizations.checkPhone']['types'],
  },
  'organizations.checkAdminPhone': {
    methods: ["GET","HEAD"],
    pattern: '/orgbuilder/organizations/check-admin-phone',
    tokens: [{"old":"/orgbuilder/organizations/check-admin-phone","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/check-admin-phone","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/check-admin-phone","type":0,"val":"check-admin-phone","end":""}],
    types: placeholder as Registry['organizations.checkAdminPhone']['types'],
  },
  'organizations.show': {
    methods: ["GET","HEAD"],
    pattern: '/orgbuilder/organizations/:id',
    tokens: [{"old":"/orgbuilder/organizations/:id","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/:id","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['organizations.show']['types'],
  },
  'organizations.edit': {
    methods: ["GET","HEAD"],
    pattern: '/orgbuilder/organizations/:id/edit',
    tokens: [{"old":"/orgbuilder/organizations/:id/edit","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/:id/edit","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/:id/edit","type":1,"val":"id","end":""},{"old":"/orgbuilder/organizations/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['organizations.edit']['types'],
  },
  'organizations.update': {
    methods: ["PUT"],
    pattern: '/orgbuilder/organizations/:id',
    tokens: [{"old":"/orgbuilder/organizations/:id","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/:id","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['organizations.update']['types'],
  },
  'organizations.superAdmin.update': {
    methods: ["PUT"],
    pattern: '/orgbuilder/organizations/:id/super-admin',
    tokens: [{"old":"/orgbuilder/organizations/:id/super-admin","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/:id/super-admin","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/:id/super-admin","type":1,"val":"id","end":""},{"old":"/orgbuilder/organizations/:id/super-admin","type":0,"val":"super-admin","end":""}],
    types: placeholder as Registry['organizations.superAdmin.update']['types'],
  },
  'organizations.superAdmin.resetPassword': {
    methods: ["POST"],
    pattern: '/orgbuilder/organizations/:id/super-admin/reset-password',
    tokens: [{"old":"/orgbuilder/organizations/:id/super-admin/reset-password","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/:id/super-admin/reset-password","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/:id/super-admin/reset-password","type":1,"val":"id","end":""},{"old":"/orgbuilder/organizations/:id/super-admin/reset-password","type":0,"val":"super-admin","end":""},{"old":"/orgbuilder/organizations/:id/super-admin/reset-password","type":0,"val":"reset-password","end":""}],
    types: placeholder as Registry['organizations.superAdmin.resetPassword']['types'],
  },
  'organizations.modules.update': {
    methods: ["PUT"],
    pattern: '/orgbuilder/organizations/:id/modules',
    tokens: [{"old":"/orgbuilder/organizations/:id/modules","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/:id/modules","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/:id/modules","type":1,"val":"id","end":""},{"old":"/orgbuilder/organizations/:id/modules","type":0,"val":"modules","end":""}],
    types: placeholder as Registry['organizations.modules.update']['types'],
  },
  'organizations.users.store': {
    methods: ["POST"],
    pattern: '/orgbuilder/organizations/:id/users',
    tokens: [{"old":"/orgbuilder/organizations/:id/users","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/:id/users","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/:id/users","type":1,"val":"id","end":""},{"old":"/orgbuilder/organizations/:id/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['organizations.users.store']['types'],
  },
  'organizations.users.update': {
    methods: ["PUT"],
    pattern: '/orgbuilder/organizations/:id/users/:userId',
    tokens: [{"old":"/orgbuilder/organizations/:id/users/:userId","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/:id/users/:userId","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/:id/users/:userId","type":1,"val":"id","end":""},{"old":"/orgbuilder/organizations/:id/users/:userId","type":0,"val":"users","end":""},{"old":"/orgbuilder/organizations/:id/users/:userId","type":1,"val":"userId","end":""}],
    types: placeholder as Registry['organizations.users.update']['types'],
  },
  'organizations.users.bulk': {
    methods: ["POST"],
    pattern: '/orgbuilder/organizations/:id/users/bulk',
    tokens: [{"old":"/orgbuilder/organizations/:id/users/bulk","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/:id/users/bulk","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/:id/users/bulk","type":1,"val":"id","end":""},{"old":"/orgbuilder/organizations/:id/users/bulk","type":0,"val":"users","end":""},{"old":"/orgbuilder/organizations/:id/users/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['organizations.users.bulk']['types'],
  },
  'organizations.profiles.index': {
    methods: ["GET","HEAD"],
    pattern: '/orgbuilder/organizations/:id/profiles',
    tokens: [{"old":"/orgbuilder/organizations/:id/profiles","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/:id/profiles","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/:id/profiles","type":1,"val":"id","end":""},{"old":"/orgbuilder/organizations/:id/profiles","type":0,"val":"profiles","end":""}],
    types: placeholder as Registry['organizations.profiles.index']['types'],
  },
  'organizations.profiles.store': {
    methods: ["POST"],
    pattern: '/orgbuilder/organizations/:id/profiles',
    tokens: [{"old":"/orgbuilder/organizations/:id/profiles","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/:id/profiles","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/:id/profiles","type":1,"val":"id","end":""},{"old":"/orgbuilder/organizations/:id/profiles","type":0,"val":"profiles","end":""}],
    types: placeholder as Registry['organizations.profiles.store']['types'],
  },
  'organizations.profiles.update': {
    methods: ["PUT"],
    pattern: '/orgbuilder/organizations/:id/profiles/:profileId',
    tokens: [{"old":"/orgbuilder/organizations/:id/profiles/:profileId","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/:id/profiles/:profileId","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/:id/profiles/:profileId","type":1,"val":"id","end":""},{"old":"/orgbuilder/organizations/:id/profiles/:profileId","type":0,"val":"profiles","end":""},{"old":"/orgbuilder/organizations/:id/profiles/:profileId","type":1,"val":"profileId","end":""}],
    types: placeholder as Registry['organizations.profiles.update']['types'],
  },
  'organizations.profiles.destroy': {
    methods: ["DELETE"],
    pattern: '/orgbuilder/organizations/:id/profiles/:profileId',
    tokens: [{"old":"/orgbuilder/organizations/:id/profiles/:profileId","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/:id/profiles/:profileId","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/:id/profiles/:profileId","type":1,"val":"id","end":""},{"old":"/orgbuilder/organizations/:id/profiles/:profileId","type":0,"val":"profiles","end":""},{"old":"/orgbuilder/organizations/:id/profiles/:profileId","type":1,"val":"profileId","end":""}],
    types: placeholder as Registry['organizations.profiles.destroy']['types'],
  },
  'organizations.profiles.permissions.update': {
    methods: ["PUT"],
    pattern: '/orgbuilder/organizations/:id/profiles/:profileId/permissions',
    tokens: [{"old":"/orgbuilder/organizations/:id/profiles/:profileId/permissions","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/:id/profiles/:profileId/permissions","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/:id/profiles/:profileId/permissions","type":1,"val":"id","end":""},{"old":"/orgbuilder/organizations/:id/profiles/:profileId/permissions","type":0,"val":"profiles","end":""},{"old":"/orgbuilder/organizations/:id/profiles/:profileId/permissions","type":1,"val":"profileId","end":""},{"old":"/orgbuilder/organizations/:id/profiles/:profileId/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['organizations.profiles.permissions.update']['types'],
  },
  'organizations.destroy': {
    methods: ["DELETE"],
    pattern: '/orgbuilder/organizations/:id',
    tokens: [{"old":"/orgbuilder/organizations/:id","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/organizations/:id","type":0,"val":"organizations","end":""},{"old":"/orgbuilder/organizations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['organizations.destroy']['types'],
  },
  'leads.index': {
    methods: ["GET","HEAD"],
    pattern: '/orgbuilder/leads',
    tokens: [{"old":"/orgbuilder/leads","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/leads","type":0,"val":"leads","end":""}],
    types: placeholder as Registry['leads.index']['types'],
  },
  'leads.store': {
    methods: ["POST"],
    pattern: '/orgbuilder/leads',
    tokens: [{"old":"/orgbuilder/leads","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/leads","type":0,"val":"leads","end":""}],
    types: placeholder as Registry['leads.store']['types'],
  },
  'leads.bulk': {
    methods: ["POST"],
    pattern: '/orgbuilder/leads/bulk',
    tokens: [{"old":"/orgbuilder/leads/bulk","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/leads/bulk","type":0,"val":"leads","end":""},{"old":"/orgbuilder/leads/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['leads.bulk']['types'],
  },
  'leads.update': {
    methods: ["PUT"],
    pattern: '/orgbuilder/leads/:id',
    tokens: [{"old":"/orgbuilder/leads/:id","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/leads/:id","type":0,"val":"leads","end":""},{"old":"/orgbuilder/leads/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leads.update']['types'],
  },
  'leads.destroy': {
    methods: ["DELETE"],
    pattern: '/orgbuilder/leads/:id',
    tokens: [{"old":"/orgbuilder/leads/:id","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/leads/:id","type":0,"val":"leads","end":""},{"old":"/orgbuilder/leads/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leads.destroy']['types'],
  },
  'masters.index': {
    methods: ["GET","HEAD"],
    pattern: '/orgbuilder/masters',
    tokens: [{"old":"/orgbuilder/masters","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/masters","type":0,"val":"masters","end":""}],
    types: placeholder as Registry['masters.index']['types'],
  },
  'masters.modules.store': {
    methods: ["POST"],
    pattern: '/orgbuilder/masters/modules',
    tokens: [{"old":"/orgbuilder/masters/modules","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/masters/modules","type":0,"val":"masters","end":""},{"old":"/orgbuilder/masters/modules","type":0,"val":"modules","end":""}],
    types: placeholder as Registry['masters.modules.store']['types'],
  },
  'masters.modules.update': {
    methods: ["PUT"],
    pattern: '/orgbuilder/masters/modules/:id',
    tokens: [{"old":"/orgbuilder/masters/modules/:id","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/masters/modules/:id","type":0,"val":"masters","end":""},{"old":"/orgbuilder/masters/modules/:id","type":0,"val":"modules","end":""},{"old":"/orgbuilder/masters/modules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['masters.modules.update']['types'],
  },
  'masters.addons.store': {
    methods: ["POST"],
    pattern: '/orgbuilder/masters/addons',
    tokens: [{"old":"/orgbuilder/masters/addons","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/masters/addons","type":0,"val":"masters","end":""},{"old":"/orgbuilder/masters/addons","type":0,"val":"addons","end":""}],
    types: placeholder as Registry['masters.addons.store']['types'],
  },
  'masters.addons.update': {
    methods: ["PUT"],
    pattern: '/orgbuilder/masters/addons/:id',
    tokens: [{"old":"/orgbuilder/masters/addons/:id","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/masters/addons/:id","type":0,"val":"masters","end":""},{"old":"/orgbuilder/masters/addons/:id","type":0,"val":"addons","end":""},{"old":"/orgbuilder/masters/addons/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['masters.addons.update']['types'],
  },
  'settings.index': {
    methods: ["GET","HEAD"],
    pattern: '/orgbuilder/settings',
    tokens: [{"old":"/orgbuilder/settings","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['settings.index']['types'],
  },
  'settings.profile.update': {
    methods: ["PUT"],
    pattern: '/orgbuilder/settings/profile',
    tokens: [{"old":"/orgbuilder/settings/profile","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/settings/profile","type":0,"val":"settings","end":""},{"old":"/orgbuilder/settings/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['settings.profile.update']['types'],
  },
  'settings.password.update': {
    methods: ["PUT"],
    pattern: '/orgbuilder/settings/password',
    tokens: [{"old":"/orgbuilder/settings/password","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/settings/password","type":0,"val":"settings","end":""},{"old":"/orgbuilder/settings/password","type":0,"val":"password","end":""}],
    types: placeholder as Registry['settings.password.update']['types'],
  },
  'settings.totp.disable': {
    methods: ["DELETE"],
    pattern: '/orgbuilder/settings/totp',
    tokens: [{"old":"/orgbuilder/settings/totp","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/settings/totp","type":0,"val":"settings","end":""},{"old":"/orgbuilder/settings/totp","type":0,"val":"totp","end":""}],
    types: placeholder as Registry['settings.totp.disable']['types'],
  },
  'settings.platform.update': {
    methods: ["PUT"],
    pattern: '/orgbuilder/settings/platform',
    tokens: [{"old":"/orgbuilder/settings/platform","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/settings/platform","type":0,"val":"settings","end":""},{"old":"/orgbuilder/settings/platform","type":0,"val":"platform","end":""}],
    types: placeholder as Registry['settings.platform.update']['types'],
  },
  'settings.orgDefaults.update': {
    methods: ["PUT"],
    pattern: '/orgbuilder/settings/org-defaults',
    tokens: [{"old":"/orgbuilder/settings/org-defaults","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/settings/org-defaults","type":0,"val":"settings","end":""},{"old":"/orgbuilder/settings/org-defaults","type":0,"val":"org-defaults","end":""}],
    types: placeholder as Registry['settings.orgDefaults.update']['types'],
  },
  'settings.users.store': {
    methods: ["POST"],
    pattern: '/orgbuilder/settings/users',
    tokens: [{"old":"/orgbuilder/settings/users","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/settings/users","type":0,"val":"settings","end":""},{"old":"/orgbuilder/settings/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['settings.users.store']['types'],
  },
  'settings.users.update': {
    methods: ["PUT"],
    pattern: '/orgbuilder/settings/users/:id',
    tokens: [{"old":"/orgbuilder/settings/users/:id","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/settings/users/:id","type":0,"val":"settings","end":""},{"old":"/orgbuilder/settings/users/:id","type":0,"val":"users","end":""},{"old":"/orgbuilder/settings/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['settings.users.update']['types'],
  },
  'settings.users.toggle': {
    methods: ["PUT"],
    pattern: '/orgbuilder/settings/users/:id/toggle',
    tokens: [{"old":"/orgbuilder/settings/users/:id/toggle","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/settings/users/:id/toggle","type":0,"val":"settings","end":""},{"old":"/orgbuilder/settings/users/:id/toggle","type":0,"val":"users","end":""},{"old":"/orgbuilder/settings/users/:id/toggle","type":1,"val":"id","end":""},{"old":"/orgbuilder/settings/users/:id/toggle","type":0,"val":"toggle","end":""}],
    types: placeholder as Registry['settings.users.toggle']['types'],
  },
  'settings.users.resetPassword': {
    methods: ["PUT"],
    pattern: '/orgbuilder/settings/users/:id/reset-password',
    tokens: [{"old":"/orgbuilder/settings/users/:id/reset-password","type":0,"val":"orgbuilder","end":""},{"old":"/orgbuilder/settings/users/:id/reset-password","type":0,"val":"settings","end":""},{"old":"/orgbuilder/settings/users/:id/reset-password","type":0,"val":"users","end":""},{"old":"/orgbuilder/settings/users/:id/reset-password","type":1,"val":"id","end":""},{"old":"/orgbuilder/settings/users/:id/reset-password","type":0,"val":"reset-password","end":""}],
    types: placeholder as Registry['settings.users.resetPassword']['types'],
  },
  'hrms.logout': {
    methods: ["POST"],
    pattern: '/hrms/logout',
    tokens: [{"old":"/hrms/logout","type":0,"val":"hrms","end":""},{"old":"/hrms/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['hrms.logout']['types'],
  },
  'hrms.self-service': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/self-service',
    tokens: [{"old":"/hrms/self-service","type":0,"val":"hrms","end":""},{"old":"/hrms/self-service","type":0,"val":"self-service","end":""}],
    types: placeholder as Registry['hrms.self-service']['types'],
  },
  'hrms.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/dashboard',
    tokens: [{"old":"/hrms/dashboard","type":0,"val":"hrms","end":""},{"old":"/hrms/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['hrms.dashboard']['types'],
  },
  'hrms.org.company': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/company',
    tokens: [{"old":"/hrms/organization/company","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/company","type":0,"val":"organization","end":""},{"old":"/hrms/organization/company","type":0,"val":"company","end":""}],
    types: placeholder as Registry['hrms.org.company']['types'],
  },
  'hrms.org.company.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/company',
    tokens: [{"old":"/hrms/organization/company","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/company","type":0,"val":"organization","end":""},{"old":"/hrms/organization/company","type":0,"val":"company","end":""}],
    types: placeholder as Registry['hrms.org.company.update']['types'],
  },
  'hrms.org.roles': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/roles',
    tokens: [{"old":"/hrms/organization/roles","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/roles","type":0,"val":"organization","end":""},{"old":"/hrms/organization/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['hrms.org.roles']['types'],
  },
  'hrms.org.hierarchy': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/hierarchy',
    tokens: [{"old":"/hrms/organization/hierarchy","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/hierarchy","type":0,"val":"organization","end":""},{"old":"/hrms/organization/hierarchy","type":0,"val":"hierarchy","end":""}],
    types: placeholder as Registry['hrms.org.hierarchy']['types'],
  },
  'hrms.org.hierarchy.store': {
    methods: ["POST"],
    pattern: '/hrms/organization/hierarchy',
    tokens: [{"old":"/hrms/organization/hierarchy","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/hierarchy","type":0,"val":"organization","end":""},{"old":"/hrms/organization/hierarchy","type":0,"val":"hierarchy","end":""}],
    types: placeholder as Registry['hrms.org.hierarchy.store']['types'],
  },
  'hrms.org.hierarchy.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/hierarchy/:id',
    tokens: [{"old":"/hrms/organization/hierarchy/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/hierarchy/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/hierarchy/:id","type":0,"val":"hierarchy","end":""},{"old":"/hrms/organization/hierarchy/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.org.hierarchy.update']['types'],
  },
  'hrms.org.hierarchy.destroy': {
    methods: ["DELETE"],
    pattern: '/hrms/organization/hierarchy/:id',
    tokens: [{"old":"/hrms/organization/hierarchy/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/hierarchy/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/hierarchy/:id","type":0,"val":"hierarchy","end":""},{"old":"/hrms/organization/hierarchy/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.org.hierarchy.destroy']['types'],
  },
  'hrms.divisions': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/divisions',
    tokens: [{"old":"/hrms/organization/settings/divisions","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/divisions","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/divisions","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/divisions","type":0,"val":"divisions","end":""}],
    types: placeholder as Registry['hrms.divisions']['types'],
  },
  'hrms.divisions.store': {
    methods: ["POST"],
    pattern: '/hrms/organization/settings/divisions',
    tokens: [{"old":"/hrms/organization/settings/divisions","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/divisions","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/divisions","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/divisions","type":0,"val":"divisions","end":""}],
    types: placeholder as Registry['hrms.divisions.store']['types'],
  },
  'hrms.divisions.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/settings/divisions/:id',
    tokens: [{"old":"/hrms/organization/settings/divisions/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/divisions/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/divisions/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/divisions/:id","type":0,"val":"divisions","end":""},{"old":"/hrms/organization/settings/divisions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.divisions.update']['types'],
  },
  'hrms.divisions.destroy': {
    methods: ["DELETE"],
    pattern: '/hrms/organization/settings/divisions/:id',
    tokens: [{"old":"/hrms/organization/settings/divisions/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/divisions/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/divisions/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/divisions/:id","type":0,"val":"divisions","end":""},{"old":"/hrms/organization/settings/divisions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.divisions.destroy']['types'],
  },
  'hrms.locations': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/locations',
    tokens: [{"old":"/hrms/organization/settings/locations","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/locations","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/locations","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/locations","type":0,"val":"locations","end":""}],
    types: placeholder as Registry['hrms.locations']['types'],
  },
  'hrms.locations.store': {
    methods: ["POST"],
    pattern: '/hrms/organization/settings/locations',
    tokens: [{"old":"/hrms/organization/settings/locations","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/locations","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/locations","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/locations","type":0,"val":"locations","end":""}],
    types: placeholder as Registry['hrms.locations.store']['types'],
  },
  'hrms.locations.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/settings/locations/:id',
    tokens: [{"old":"/hrms/organization/settings/locations/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/locations/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/locations/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/locations/:id","type":0,"val":"locations","end":""},{"old":"/hrms/organization/settings/locations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.locations.update']['types'],
  },
  'hrms.locations.destroy': {
    methods: ["DELETE"],
    pattern: '/hrms/organization/settings/locations/:id',
    tokens: [{"old":"/hrms/organization/settings/locations/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/locations/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/locations/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/locations/:id","type":0,"val":"locations","end":""},{"old":"/hrms/organization/settings/locations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.locations.destroy']['types'],
  },
  'hrms.departments': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/departments',
    tokens: [{"old":"/hrms/organization/settings/departments","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/departments","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/departments","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/departments","type":0,"val":"departments","end":""}],
    types: placeholder as Registry['hrms.departments']['types'],
  },
  'hrms.departments.store': {
    methods: ["POST"],
    pattern: '/hrms/organization/settings/departments',
    tokens: [{"old":"/hrms/organization/settings/departments","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/departments","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/departments","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/departments","type":0,"val":"departments","end":""}],
    types: placeholder as Registry['hrms.departments.store']['types'],
  },
  'hrms.departments.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/settings/departments/:id',
    tokens: [{"old":"/hrms/organization/settings/departments/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/departments/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/departments/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/departments/:id","type":0,"val":"departments","end":""},{"old":"/hrms/organization/settings/departments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.departments.update']['types'],
  },
  'hrms.departments.destroy': {
    methods: ["DELETE"],
    pattern: '/hrms/organization/settings/departments/:id',
    tokens: [{"old":"/hrms/organization/settings/departments/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/departments/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/departments/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/departments/:id","type":0,"val":"departments","end":""},{"old":"/hrms/organization/settings/departments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.departments.destroy']['types'],
  },
  'hrms.sub-departments': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/sub-departments',
    tokens: [{"old":"/hrms/organization/settings/sub-departments","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/sub-departments","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/sub-departments","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/sub-departments","type":0,"val":"sub-departments","end":""}],
    types: placeholder as Registry['hrms.sub-departments']['types'],
  },
  'hrms.sub-departments.store': {
    methods: ["POST"],
    pattern: '/hrms/organization/settings/sub-departments',
    tokens: [{"old":"/hrms/organization/settings/sub-departments","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/sub-departments","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/sub-departments","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/sub-departments","type":0,"val":"sub-departments","end":""}],
    types: placeholder as Registry['hrms.sub-departments.store']['types'],
  },
  'hrms.sub-departments.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/settings/sub-departments/:id',
    tokens: [{"old":"/hrms/organization/settings/sub-departments/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/sub-departments/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/sub-departments/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/sub-departments/:id","type":0,"val":"sub-departments","end":""},{"old":"/hrms/organization/settings/sub-departments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.sub-departments.update']['types'],
  },
  'hrms.sub-departments.destroy': {
    methods: ["DELETE"],
    pattern: '/hrms/organization/settings/sub-departments/:id',
    tokens: [{"old":"/hrms/organization/settings/sub-departments/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/sub-departments/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/sub-departments/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/sub-departments/:id","type":0,"val":"sub-departments","end":""},{"old":"/hrms/organization/settings/sub-departments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.sub-departments.destroy']['types'],
  },
  'hrms.designations': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/designations',
    tokens: [{"old":"/hrms/organization/settings/designations","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/designations","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/designations","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/designations","type":0,"val":"designations","end":""}],
    types: placeholder as Registry['hrms.designations']['types'],
  },
  'hrms.designations.store': {
    methods: ["POST"],
    pattern: '/hrms/organization/settings/designations',
    tokens: [{"old":"/hrms/organization/settings/designations","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/designations","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/designations","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/designations","type":0,"val":"designations","end":""}],
    types: placeholder as Registry['hrms.designations.store']['types'],
  },
  'hrms.designations.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/settings/designations/:id',
    tokens: [{"old":"/hrms/organization/settings/designations/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/designations/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/designations/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/designations/:id","type":0,"val":"designations","end":""},{"old":"/hrms/organization/settings/designations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.designations.update']['types'],
  },
  'hrms.designations.destroy': {
    methods: ["DELETE"],
    pattern: '/hrms/organization/settings/designations/:id',
    tokens: [{"old":"/hrms/organization/settings/designations/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/designations/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/designations/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/designations/:id","type":0,"val":"designations","end":""},{"old":"/hrms/organization/settings/designations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.designations.destroy']['types'],
  },
  'hrms.grades': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/grades',
    tokens: [{"old":"/hrms/organization/settings/grades","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/grades","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/grades","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/grades","type":0,"val":"grades","end":""}],
    types: placeholder as Registry['hrms.grades']['types'],
  },
  'hrms.grades.store': {
    methods: ["POST"],
    pattern: '/hrms/organization/settings/grades',
    tokens: [{"old":"/hrms/organization/settings/grades","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/grades","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/grades","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/grades","type":0,"val":"grades","end":""}],
    types: placeholder as Registry['hrms.grades.store']['types'],
  },
  'hrms.grades.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/settings/grades/:id',
    tokens: [{"old":"/hrms/organization/settings/grades/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/grades/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/grades/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/grades/:id","type":0,"val":"grades","end":""},{"old":"/hrms/organization/settings/grades/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.grades.update']['types'],
  },
  'hrms.grades.destroy': {
    methods: ["DELETE"],
    pattern: '/hrms/organization/settings/grades/:id',
    tokens: [{"old":"/hrms/organization/settings/grades/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/grades/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/grades/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/grades/:id","type":0,"val":"grades","end":""},{"old":"/hrms/organization/settings/grades/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.grades.destroy']['types'],
  },
  'hrms.sections': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/sections',
    tokens: [{"old":"/hrms/organization/settings/sections","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/sections","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/sections","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/sections","type":0,"val":"sections","end":""}],
    types: placeholder as Registry['hrms.sections']['types'],
  },
  'hrms.sections.store': {
    methods: ["POST"],
    pattern: '/hrms/organization/settings/sections',
    tokens: [{"old":"/hrms/organization/settings/sections","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/sections","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/sections","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/sections","type":0,"val":"sections","end":""}],
    types: placeholder as Registry['hrms.sections.store']['types'],
  },
  'hrms.sections.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/settings/sections/:id',
    tokens: [{"old":"/hrms/organization/settings/sections/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/sections/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/sections/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/sections/:id","type":0,"val":"sections","end":""},{"old":"/hrms/organization/settings/sections/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.sections.update']['types'],
  },
  'hrms.sections.destroy': {
    methods: ["DELETE"],
    pattern: '/hrms/organization/settings/sections/:id',
    tokens: [{"old":"/hrms/organization/settings/sections/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/sections/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/sections/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/sections/:id","type":0,"val":"sections","end":""},{"old":"/hrms/organization/settings/sections/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.sections.destroy']['types'],
  },
  'hrms.sub-sections': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/sub-sections',
    tokens: [{"old":"/hrms/organization/settings/sub-sections","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/sub-sections","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/sub-sections","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/sub-sections","type":0,"val":"sub-sections","end":""}],
    types: placeholder as Registry['hrms.sub-sections']['types'],
  },
  'hrms.sub-sections.store': {
    methods: ["POST"],
    pattern: '/hrms/organization/settings/sub-sections',
    tokens: [{"old":"/hrms/organization/settings/sub-sections","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/sub-sections","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/sub-sections","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/sub-sections","type":0,"val":"sub-sections","end":""}],
    types: placeholder as Registry['hrms.sub-sections.store']['types'],
  },
  'hrms.sub-sections.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/settings/sub-sections/:id',
    tokens: [{"old":"/hrms/organization/settings/sub-sections/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/sub-sections/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/sub-sections/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/sub-sections/:id","type":0,"val":"sub-sections","end":""},{"old":"/hrms/organization/settings/sub-sections/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.sub-sections.update']['types'],
  },
  'hrms.sub-sections.destroy': {
    methods: ["DELETE"],
    pattern: '/hrms/organization/settings/sub-sections/:id',
    tokens: [{"old":"/hrms/organization/settings/sub-sections/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/sub-sections/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/sub-sections/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/sub-sections/:id","type":0,"val":"sub-sections","end":""},{"old":"/hrms/organization/settings/sub-sections/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.sub-sections.destroy']['types'],
  },
  'hrms.holidays': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/holidays',
    tokens: [{"old":"/hrms/organization/settings/holidays","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/holidays","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/holidays","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/holidays","type":0,"val":"holidays","end":""}],
    types: placeholder as Registry['hrms.holidays']['types'],
  },
  'hrms.holidays.store': {
    methods: ["POST"],
    pattern: '/hrms/organization/settings/holidays',
    tokens: [{"old":"/hrms/organization/settings/holidays","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/holidays","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/holidays","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/holidays","type":0,"val":"holidays","end":""}],
    types: placeholder as Registry['hrms.holidays.store']['types'],
  },
  'hrms.holidays.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/settings/holidays/:id',
    tokens: [{"old":"/hrms/organization/settings/holidays/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/holidays/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/holidays/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/holidays/:id","type":0,"val":"holidays","end":""},{"old":"/hrms/organization/settings/holidays/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.holidays.update']['types'],
  },
  'hrms.holidays.destroy': {
    methods: ["DELETE"],
    pattern: '/hrms/organization/settings/holidays/:id',
    tokens: [{"old":"/hrms/organization/settings/holidays/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/holidays/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/holidays/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/holidays/:id","type":0,"val":"holidays","end":""},{"old":"/hrms/organization/settings/holidays/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.holidays.destroy']['types'],
  },
  'hrms.notice-period': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/notice-period',
    tokens: [{"old":"/hrms/organization/settings/notice-period","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/notice-period","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/notice-period","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/notice-period","type":0,"val":"notice-period","end":""}],
    types: placeholder as Registry['hrms.notice-period']['types'],
  },
  'hrms.notice-period.store': {
    methods: ["POST"],
    pattern: '/hrms/organization/settings/notice-period',
    tokens: [{"old":"/hrms/organization/settings/notice-period","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/notice-period","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/notice-period","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/notice-period","type":0,"val":"notice-period","end":""}],
    types: placeholder as Registry['hrms.notice-period.store']['types'],
  },
  'hrms.notice-period.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/settings/notice-period/:id',
    tokens: [{"old":"/hrms/organization/settings/notice-period/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/notice-period/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/notice-period/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/notice-period/:id","type":0,"val":"notice-period","end":""},{"old":"/hrms/organization/settings/notice-period/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.notice-period.update']['types'],
  },
  'hrms.notice-period.destroy': {
    methods: ["DELETE"],
    pattern: '/hrms/organization/settings/notice-period/:id',
    tokens: [{"old":"/hrms/organization/settings/notice-period/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/notice-period/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/notice-period/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/notice-period/:id","type":0,"val":"notice-period","end":""},{"old":"/hrms/organization/settings/notice-period/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.notice-period.destroy']['types'],
  },
  'hrms.approvals': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/approvals',
    tokens: [{"old":"/hrms/organization/settings/approvals","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/approvals","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/approvals","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/approvals","type":0,"val":"approvals","end":""}],
    types: placeholder as Registry['hrms.approvals']['types'],
  },
  'hrms.approvals.store': {
    methods: ["POST"],
    pattern: '/hrms/organization/settings/approvals',
    tokens: [{"old":"/hrms/organization/settings/approvals","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/approvals","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/approvals","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/approvals","type":0,"val":"approvals","end":""}],
    types: placeholder as Registry['hrms.approvals.store']['types'],
  },
  'hrms.approvals.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/settings/approvals/:id',
    tokens: [{"old":"/hrms/organization/settings/approvals/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/approvals/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/approvals/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/approvals/:id","type":0,"val":"approvals","end":""},{"old":"/hrms/organization/settings/approvals/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.approvals.update']['types'],
  },
  'hrms.approvals.destroy': {
    methods: ["DELETE"],
    pattern: '/hrms/organization/settings/approvals/:id',
    tokens: [{"old":"/hrms/organization/settings/approvals/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/approvals/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/approvals/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/approvals/:id","type":0,"val":"approvals","end":""},{"old":"/hrms/organization/settings/approvals/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.approvals.destroy']['types'],
  },
  'hrms.documents': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/documents',
    tokens: [{"old":"/hrms/organization/settings/documents","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/documents","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/documents","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/documents","type":0,"val":"documents","end":""}],
    types: placeholder as Registry['hrms.documents']['types'],
  },
  'hrms.documents.store': {
    methods: ["POST"],
    pattern: '/hrms/organization/settings/documents',
    tokens: [{"old":"/hrms/organization/settings/documents","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/documents","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/documents","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/documents","type":0,"val":"documents","end":""}],
    types: placeholder as Registry['hrms.documents.store']['types'],
  },
  'hrms.documents.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/settings/documents/:id',
    tokens: [{"old":"/hrms/organization/settings/documents/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/documents/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/documents/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/documents/:id","type":0,"val":"documents","end":""},{"old":"/hrms/organization/settings/documents/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.documents.update']['types'],
  },
  'hrms.documents.destroy': {
    methods: ["DELETE"],
    pattern: '/hrms/organization/settings/documents/:id',
    tokens: [{"old":"/hrms/organization/settings/documents/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/documents/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/documents/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/documents/:id","type":0,"val":"documents","end":""},{"old":"/hrms/organization/settings/documents/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.documents.destroy']['types'],
  },
  'hrms.checklists': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/checklists',
    tokens: [{"old":"/hrms/organization/settings/checklists","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/checklists","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/checklists","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/checklists","type":0,"val":"checklists","end":""}],
    types: placeholder as Registry['hrms.checklists']['types'],
  },
  'hrms.checklists.store': {
    methods: ["POST"],
    pattern: '/hrms/organization/settings/checklists',
    tokens: [{"old":"/hrms/organization/settings/checklists","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/checklists","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/checklists","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/checklists","type":0,"val":"checklists","end":""}],
    types: placeholder as Registry['hrms.checklists.store']['types'],
  },
  'hrms.checklists.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/settings/checklists/:id',
    tokens: [{"old":"/hrms/organization/settings/checklists/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/checklists/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/checklists/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/checklists/:id","type":0,"val":"checklists","end":""},{"old":"/hrms/organization/settings/checklists/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.checklists.update']['types'],
  },
  'hrms.checklists.destroy': {
    methods: ["DELETE"],
    pattern: '/hrms/organization/settings/checklists/:id',
    tokens: [{"old":"/hrms/organization/settings/checklists/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/checklists/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/checklists/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/checklists/:id","type":0,"val":"checklists","end":""},{"old":"/hrms/organization/settings/checklists/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.checklists.destroy']['types'],
  },
  'hrms.templates': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/templates',
    tokens: [{"old":"/hrms/organization/settings/templates","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/templates","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/templates","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/templates","type":0,"val":"templates","end":""}],
    types: placeholder as Registry['hrms.templates']['types'],
  },
  'hrms.templates.store': {
    methods: ["POST"],
    pattern: '/hrms/organization/settings/templates',
    tokens: [{"old":"/hrms/organization/settings/templates","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/templates","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/templates","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/templates","type":0,"val":"templates","end":""}],
    types: placeholder as Registry['hrms.templates.store']['types'],
  },
  'hrms.templates.update': {
    methods: ["PUT"],
    pattern: '/hrms/organization/settings/templates/:id',
    tokens: [{"old":"/hrms/organization/settings/templates/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/templates/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/templates/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/templates/:id","type":0,"val":"templates","end":""},{"old":"/hrms/organization/settings/templates/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.templates.update']['types'],
  },
  'hrms.templates.destroy': {
    methods: ["DELETE"],
    pattern: '/hrms/organization/settings/templates/:id',
    tokens: [{"old":"/hrms/organization/settings/templates/:id","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/templates/:id","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/templates/:id","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/templates/:id","type":0,"val":"templates","end":""},{"old":"/hrms/organization/settings/templates/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hrms.templates.destroy']['types'],
  },
  'hrms.alerts': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/alerts',
    tokens: [{"old":"/hrms/organization/settings/alerts","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/alerts","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/alerts","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/alerts","type":0,"val":"alerts","end":""}],
    types: placeholder as Registry['hrms.alerts']['types'],
  },
  'hrms.notifications': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/notifications',
    tokens: [{"old":"/hrms/organization/settings/notifications","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/notifications","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/notifications","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/notifications","type":0,"val":"notifications","end":""}],
    types: placeholder as Registry['hrms.notifications']['types'],
  },
  'hrms.fiscal-year': {
    methods: ["GET","HEAD"],
    pattern: '/hrms/organization/settings/fiscal-year',
    tokens: [{"old":"/hrms/organization/settings/fiscal-year","type":0,"val":"hrms","end":""},{"old":"/hrms/organization/settings/fiscal-year","type":0,"val":"organization","end":""},{"old":"/hrms/organization/settings/fiscal-year","type":0,"val":"settings","end":""},{"old":"/hrms/organization/settings/fiscal-year","type":0,"val":"fiscal-year","end":""}],
    types: placeholder as Registry['hrms.fiscal-year']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
